export const ENV_VAR = Object.freeze({
  FIREBASE_API_KEY: 'FIREBASE_API_KEY',
  FIREBASE_AUTH_DOMIAN: 'FIREBASE_AUTH_DOMIAN',
  FIREBASE_PROJECT_ID: 'FIREBASE_PROJECT_ID',
  FIREBASE_STORAGE_BUCKET: 'FIREBASE_STORAGE_BUCKET',
  FIREBASE_MESSAGING_SENDER_ID: 'FIREBASE_MESSAGING_SENDER_ID',
  FIREBASE_APP_ID: 'FIREBASE_APP_ID',
  FIREBASE_DATABASE_URL: 'FIREBASE_DATABASE_URL',
});